# Generated by Django 3.2.4 on 2021-08-22 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=250, null=True)),
                ('g_model', models.CharField(max_length=250, null=True)),
                ('title', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('link', models.CharField(max_length=1000, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('g_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finder.list')),
            ],
        ),
    ]
