# Generated by Django 3.2.4 on 2021-08-25 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_tracker', '0001_initial'),
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='g_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list_tracker.list'),
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
