# Generated by Django 3.2.4 on 2021-08-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_remove_guitar_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guitar',
            name='price',
        ),
    ]
