# Generated by Django 3.2.4 on 2021-08-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_remove_guitar_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
