# Generated by Django 3.2.4 on 2021-08-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0006_auto_20210827_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='articles',
            field=models.IntegerField(default=0),
        ),
    ]
