# Generated by Django 3.2.4 on 2021-08-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0007_search_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='price',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
