# Generated by Django 3.2.4 on 2021-08-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0008_alter_guitar_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
